# Generated by Django 4.0 on 2023-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
