# Generated by Django 4.0 on 2023-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
