# Generated by Django 4.0 on 2023-04-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0003_user_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template', models.TextField(blank=True, max_length=5000, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermailtemplate', to='app_phishing.user')),
            ],
        ),
    ]
