# Generated by Django 4.0 on 2023-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0004_usermailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Link-geklickt'),
        ),
        migrations.AlterField(
            model_name='usermailtemplate',
            name='email_template',
            field=models.TextField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='usermailtemplate',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Email-geschickt'),
        ),
    ]
