# Generated by Django 4.0 on 2023-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0005_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='open_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Link geöffnet am:'),
        ),
    ]
