# Generated by Django 4.0 on 2023-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0008_alter_user_user_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailtemplate',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='erstellt am:'),
        ),
    ]
