# Generated by Django 4.0 on 2023-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0009_usermailtemplate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailtemplate',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email gesendet am:'),
        ),
        migrations.AlterField(
            model_name='usermailtemplate',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am:'),
        ),
    ]
